### ISSUE TITLE
How to analyze scATAC-seq data without whitelist?

### ISSUE THREAD

**Issue by HailinWei98** [haowenz/chromap#40] opened 2021-11-29 07:40 UTC
Hi,
I have tried chromap on public scATAC-seq data without whitelist. If I use the command <code>--barcode-whitelist None</code>, which is supported in <b>STAR</b>, the output bed file is empty. If I generate a whitelist by myself, using all barcodes in fastq file, chromap raised an error as follows :
<code>chromap: src/chromap.cc:5466: void chromap::Chromap<MappingRecord>::LoadBarcodeWhitelist() [with MappingRecord = chromap::PairedEndMappingWithBarcode]: Assertion `khash_return_code != -1 && khash_return_code != 0' failed.
Aborted (core dumped)</code>
So how to analyze scATAC-seq data without whitelist using chromap?
Best,
Hailin

**Comment by haowenz** [comment] 2021-11-29 14:24
If you don't have whitelist, just don't specify `--barcode-whitelist` in your command line. Then Chromap will still map the scATAC-seq data without barcode correction.

**Comment by HailinWei98** [comment] 2021-11-29 14:48
This is my command without specifying <code>--barcode-whitelist</code> : 
<code>chromap --preset atac -x alignment/hg38.index  -r gtf/Homo_sapiens.GRCh38.dna.primary_assembly.fa -1 data/Spear-ATAC/SRR13959153.1_1.fastq -2 data/Spear-ATAC/SRR13959153.1_3.fastq -o alignment/atac.bed --barcode data/Spear-ATAC/SRR13959153.1_2.fastq</code>
but chromap also raise an error message <code>There are input barcode files but a barcode whitelist file is missing!</code>.So what's wrong with my command?

**Comment by HailinWei98** [comment] 2021-11-29 14:49
This is my command without specifying <code>--barcode-whitelist</code> : 
<code>chromap --preset atac -x alignment/hg38.index  -r gtf/Homo_sapiens.GRCh38.dna.primary_assembly.fa -1 data/Spear-ATAC/SRR13959153.1_1.fastq -2 data/Spear-ATAC/SRR13959153.1_3.fastq -o alignment/atac.bed --barcode data/Spear-ATAC/SRR13959153.1_2.fastq</code>
but chromap also raise an error message <code>There are input barcode files but a barcode whitelist file is missing!</code>.So what's wrong with my command?

**Comment by haowenz** [comment] 2021-11-29 14:59
I just looked at the Chromap code. It seems that we made barcode whitelist a mandatory input at some time point, which is not as expected. We will generate a fix for this soon. I will let you know once we are done on that on the source code of master branch. If you used Conda to install Chromap, it will take some time for Chromap to get updated on Conda.

For now you may use the barcode whitelist you generated. The error you are getting is most likely caused by duplicated barcode in the whitelist you generated. Please double check the barcode whitelist file you generated and make sure there is no duplicated barcode inside it and try it again.

**Comment by HailinWei98** [comment] 2021-11-30 02:18
I have checked my whitelist file and make sure all barcodes inside are unique, but it also raise the same error as I first mentioned. The barcodes in whitelist are as follows:
AAAAAAAAAAAAAAAC
AAAAAAAAAAAAAACC
AAAAAAAAAAAAACCC
AAAAAAAAAAAAATAC
AAAAAAAAAAAAATCC
AAAAAAAAAAAACACC
AAAAAAAAAAAACCAC
AAAAAAAAAAAACCCC
AAAAAAAAAAAATCCG
AAAAAAAAAAACAACC
and it's derived from fastq file of barcodes.So maybe the format(.txt file) of my whitelist file is wrong?

**Comment by haowenz** [comment] 2021-12-01 16:35
> I have checked my whitelist file and make sure all barcodes inside are unique, but it also raise the same error as I first mentioned. The barcodes in whitelist are as follows:
> AAAAAAAAAAAAAAAC
> AAAAAAAAAAAAAACC
> AAAAAAAAAAAAACCC
> AAAAAAAAAAAAATAC
> AAAAAAAAAAAAATCC
> AAAAAAAAAAAACACC
> AAAAAAAAAAAACCAC
> AAAAAAAAAAAACCCC
> AAAAAAAAAAAATCCG
> AAAAAAAAAAACAACC
> and it's derived from fastq file of barcodes.So maybe the format(.txt file) of my whitelist file is wrong?

I just tried to run Chromap with this barcode whitelist and Chromap was able to load this whitelist and use it. This is weird. Can you tell us which version of Chromap you are using and the way you installed it?

**Comment by HailinWei98** [comment] 2021-12-02 12:50
> > I have checked my whitelist file and make sure all barcodes inside are unique, but it also raise the same error as I first mentioned. The barcodes in whitelist are as follows:
> > AAAAAAAAAAAAAAAC
> > AAAAAAAAAAAAAACC
> > AAAAAAAAAAAAACCC
> > AAAAAAAAAAAAATAC
> > AAAAAAAAAAAAATCC
> > AAAAAAAAAAAACACC
> > AAAAAAAAAAAACCAC
> > AAAAAAAAAAAACCCC
> > AAAAAAAAAAAATCCG
> > AAAAAAAAAAACAACC
> > and it's derived from fastq file of barcodes.So maybe the format(.txt file) of my whitelist file is wrong?
> 
> I just tried to run Chromap with this barcode whitelist and Chromap was able to load this whitelist and use it. This is weird. Can you tell us which version of Chromap you are using and the way you installed it?

I tried more barcodes in my whitelist to run Chromap, and found that some barcodes like <code>AAAAAAAAAAACAACN</code> in whitelist file maybe the cause of the error, which includes N in barcode sequence. After removing these barcodes from my whitelist, I got the correct bed file as output.
Thanks for your patience and answers !!

**Comment by HailinWei98** [comment] 2021-12-02 12:51
> > I have checked my whitelist file and make sure all barcodes inside are unique, but it also raise the same error as I first mentioned. The barcodes in whitelist are as follows:
> > AAAAAAAAAAAAAAAC
> > AAAAAAAAAAAAAACC
> > AAAAAAAAAAAAACCC
> > AAAAAAAAAAAAATAC
> > AAAAAAAAAAAAATCC
> > AAAAAAAAAAAACACC
> > AAAAAAAAAAAACCAC
> > AAAAAAAAAAAACCCC
> > AAAAAAAAAAAATCCG
> > AAAAAAAAAAACAACC
> > and it's derived from fastq file of barcodes.So maybe the format(.txt file) of my whitelist file is wrong?
> 
> I just tried to run Chromap with this barcode whitelist and Chromap was able to load this whitelist and use it. This is weird. Can you tell us which version of Chromap you are using and the way you installed it?

I tried more barcodes in my whitelist to run Chromap, and found that some barcodes like <code>AAAAAAAAAAACAACN</code> in whitelist file maybe the cause of the error, which includes N in barcode sequence. After removing these barcodes from my whitelist, I got the correct bed file as output.
Thanks for your patience and answers !!

**Comment by haowenz** [comment] 2021-12-02 14:50
> > > I have checked my whitelist file and make sure all barcodes inside are unique, but it also raise the same error as I first mentioned. The barcodes in whitelist are as follows:
> > > AAAAAAAAAAAAAAAC
> > > AAAAAAAAAAAAAACC
> > > AAAAAAAAAAAAACCC
> > > AAAAAAAAAAAAATAC
> > > AAAAAAAAAAAAATCC
> > > AAAAAAAAAAAACACC
> > > AAAAAAAAAAAACCAC
> > > AAAAAAAAAAAACCCC
> > > AAAAAAAAAAAATCCG
> > > AAAAAAAAAAACAACC
> > > and it's derived from fastq file of barcodes.So maybe the format(.txt file) of my whitelist file is wrong?
> > 
> > 
> > I just tried to run Chromap with this barcode whitelist and Chromap was able to load this whitelist and use it. This is weird. Can you tell us which version of Chromap you are using and the way you installed it?
> 
> I tried more barcodes in my whitelist to run Chromap, and found that some barcodes like `AAAAAAAAAAACAACN` in whitelist file maybe the cause of the error, which includes N in barcode sequence. After removing these barcodes from my whitelist, I got the correct bed file as output. Thanks for your patience and answers !!

Good to know you were able to resolve this problem. We will generate a more informative warning when there are Ns in the barcode whitelist.

**Closed** 2021-12-08 21:14 UTC
Labels: bug, enhancement
