### ISSUE TITLE
SAM output stdout fail and cannot convert to bam

### ISSUE THREAD

**Issue by baozg** [haowenz/chromap#50] opened 2021-12-22 07:51 UTC
Hi, @haowenz 

I use the `chromap` to mapping HiC reads to a plant genome for scaffolding. But it fail when I set the output to `/dev/stdout`. It throw the error 
```bash
chromap: src/output_tools.cc:348: void chromap::OutputTools<MappingRecord>::OutputTempMapping(const string&, uint32_t, const std::vector<std::vector<MappingRecord> >&)
 [with MappingRecord = chromap::SAMMapping; std::string = std::__cxx11::basic_string<char>; uint32_t = unsigned int]: Assertion `temp_mapping_output_file != __null' failed.
```

When I try to ouptut to a file `M32.temp.sam` then covert to the bam format, the `chromap` run successfully but the `samtools` throw the error 
```
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 20315
[main_samview] truncated file.

# line 20315
A00234:853:HTT5VDSX2:3:2675:19777:22623 179     utg000001l      38590   9       104M    *       0       0       ACAGTCCAAAATCAGTCGTTTTTGCTGGAAACTAACCTTGAACCAATCACACATGAGCAAGAATGCTCTGATACCAATTGTAGGTCCCTCTGGGTTGGATCATCCTTAATTCGTTGCTTACTTCATACCACCAGGTTGTTATGAACTATA   FF::FFFFFFFFFFFFFFFFFFF:F:FFFFF::FFFF:FF:FFFFFF:F:FFF,,F::FFFFFFFFFFFFFFFFF:FF:FFFFFFFFF:F,FFFFFFFFFFFF,FFFFF:F,FFF,FFFFFFF:FFFFFFF,FF,FFF:FFFF:F::FFF   NM:i:2  MD:Z:T1A101
``` 

Here is the command I use

```bash
chromap -i -r M32.contigs.fa -o M32.index
#stdout output
chromap --preset hic -x M32.index -r assembly.fa -t 12 -q 30 -1 M32.Clean.R1.part_001.fq.gz -2  M32.Clean.R2.part_001.fq.gz --SAM -o /dev/stdout | samtools view -t 12 -Shb -o M32.chromap.bam

#sam file
chromap --preset hic -x M32.index -r assembly.fa -t 12 -1 M32.Clean.R1.part_001.fq.gz -2  M32.Clean.R2.part_001.fq.gz --SAM -o M32.temp.sam
samtools view -t 12 -Shb -o M32.chromap.bam M32.temp.sam

```

log

```bash

# stdout
Preset parameters for Hi-C are used.
Start to map reads.
Parameters: error threshold: 4, min-num-seeds: 2, max-seed-frequency: 500,1000, max-num-best-mappings: 1, max-insert-size: 1000, MAPQ-threshold: 30, min-read-length: $
0, bc-error-threshold: 1, bc-probability-threshold: 0.90
Number of threads: 12
Analyze bulk data.
Won't try to remove adapters on 3'.
Won't remove PCR duplicates after mapping.
Will remove PCR duplicates at bulk level.
Won't allocate multi-mappings after mapping.
Only output unique mappings after mapping.
Only output mappings of which barcodes are in whitelist.
Allow split alignment.
Output mappings in SAM format.
Reference file: assembly.fa
Index file: M32.index
1th read 1 file: M32.Clean.R1.part_001.fq.gz
1th read 2 file: M32.Clean.R2.part_001.fq.gz
Output file: /dev/stdout
Loaded all sequences successfully in 6.41s, number of sequences: 20307, number of bases: 4462388593.
Kmer size: 17, window size: 7.
Lookup table size: 185123217, occurrence table size: 1044627066.
Loaded index successfully in 30.42s.
Mapped 500000 read pairs in 88.24s.
Mapped 500000 read pairs in 33.60s.
Mapped 500000 read pairs in 29.44s.
Mapped 500000 read pairs in 30.84s.
chromap: src/output_tools.cc:348: void chromap::OutputTools<MappingRecord>::OutputTempMapping(const string&, uint32_t, const std::vector<std::vector<MappingRecord> >&)
 [with MappingRecord = chromap::SAMMapping; std::string = std::__cxx11::basic_string<char>; uint32_t = unsigned int]: Assertion `temp_mapping_output_file != __null' fa
iled.
```

sam file log
```bash
Preset parameters for Hi-C are used.
Start to map reads.
Parameters: error threshold: 4, min-num-seeds: 2, max-seed-frequency: 500,1000, max-num-best-mappings: 1, max-insert-size: 1000, MAPQ-threshold: 1, min-read-length: 30, bc-error-threshold: 1, bc-probability-threshold: 0.90
Number of threads: 12
Analyze bulk data.
Won't try to remove adapters on 3'.
Won't remove PCR duplicates after mapping.
Will remove PCR duplicates at bulk level.
Won't allocate multi-mappings after mapping.
Only output unique mappings after mapping.
Only output mappings of which barcodes are in whitelist.
Allow split alignment.
Output mappings in SAM format.
Reference file: assembly.fa
Index file: M32.index
1th read 1 file: M32.Clean.R1.part_001.fq.gz
1th read 2 file: M32.Clean.R2.part_001.fq.gz
Output file: M32.temp.sam
Loaded all sequences successfully in 34.30s, number of sequences: 20307, number of bases: 4462388593.
Kmer size: 17, window size: 7.
Lookup table size: 185123217, occurrence table size: 1044627066.
Loaded index successfully in 97.68s.
Mapped 500000 read pairs in 78.43s.
Mapped 500000 read pairs in 30.17s.
Mapped 500000 read pairs in 26.05s.
Mapped 500000 read pairs in 27.59s.
Mapped 500000 read pairs in 30.56s.
Mapped 500000 read pairs in 23.35s.
Mapped 500000 read pairs in 22.57s.
Mapped 500000 read pairs in 22.78s.
Mapped 500000 read pairs in 27.67s.
Mapped 500000 read pairs in 21.89s.
Mapped 500000 read pairs in 21.94s.
Mapped 500000 read pairs in 22.07s.
Mapped 500000 read pairs in 28.24s.
Mapped 500000 read pairs in 22.09s.
Mapped 500000 read pairs in 21.25s.
Mapped 500000 read pairs in 22.55s.
Mapped 500000 read pairs in 26.80s.
Mapped 500000 read pairs in 22.42s.
Mapped 500000 read pairs in 21.73s.
Mapped 500000 read pairs in 20.30s.
Mapped 500000 read pairs in 25.67s.
Mapped 500000 read pairs in 21.24s.
Mapped 500000 read pairs in 22.29s.
Mapped 500000 read pairs in 22.39s.
Mapped 496659 read pairs in 25.47s.
Mapped all reads in 660.55s.
Number of reads: 24993318.
Number of mapped reads: 21819532.
Number of uniquely mapped reads: 9274894.
Number of reads have multi-mappings: 12544638.
Number of candidates: 7360165941.
Number of mappings: 21819532.
Number of uni-mappings: 9274894.
Number of multi-mappings: 12544638.
Sorted and outputed mappings in 64.57s.
# uni-mappings: 17821250, # multi-mappings: 3998242, total: 21819492.
Number of output mappings (passed filters): 6701518
Total time: 873.62s.

[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 20315
[main_samview] truncated file.

# line 20315
A00234:853:HTT5VDSX2:3:2675:19777:22623 179     utg000001l      38590   9       104M    *       0       0       ACAGTCCAAAATCAGTCGTTTTTGCTGGAAACTAACCTTGAACCAATCACACATGAGCAAGAATGCTCTGATACCAATTGTAGGTCCCTCTGGGTTGGATCATCCTTAATTCGTTGCTTACTTCATACCACCAGGTTGTTATGAACTATA   FF::FFFFFFFFFFFFFFFFFFF:F:FFFFF::FFFF:FF:FFFFFF:F:FFF,,F::FFFFFFFFFFFFFFFFF:FF:FFFFFFFFF:F,FFFFFFFFFFFF,FFFFF:F,FFF,FFFFFFF:FFFFFFF,FF,FFF:FFFF:F::FFF   NM:i:2  MD:Z:T1A101
```

**Comment by mourisl** [comment] 2021-12-22 14:25
The --hic option implicitly uses --low-mem option, which needs to generate temporary files using the prefix of the -o option. I don't think you can create a file in the folder /dev/ folder so Chromap could not generate the temporary files. In this case, you can either generate sam->bam as you already did, or run Chromap with the option "-o /dev/stdout --split-alignment --pairs" instead of "--hic". Your data is not very large, so the memory usage should not increase much.

We will find a better solution in the future. Thanks.

**Comment by baozg** [comment] 2021-12-22 16:17
But when I use the the sam->bam, the `samtools` throw the error 

```
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 20315
[main_samview] truncated file.
```

**Comment by cpadillla1331** [comment] 2022-01-14 03:26
I run into the sam error too

**Comment by haowenz** [comment] 2022-01-14 05:11
Which Chromap version did you use? 

It seems that in your example the cigar length is 104 and the sequence length is 150, which is the full read length. I thought this was fixed in #29, where we forgot to trim the sequence before we output it. But it seems the problem is still there with your example. I will double check and fix this problem if it is still there in next release.

**Comment by baozg** [comment] 2022-01-14 05:17
chromap (0.1.3) installed from the conda

**Comment by haowenz** [comment] 2022-01-14 05:29
> chromap (0.1.3) installed from the conda. I can try the latest 0.1.4 for small test data. Stay tuned.

Hi, 

No need to try that. I just located the problem. It is a bug with the SAM output and the sequence is not trimmed properly in the SAM output. I will generate a fix tomorrow. It would be great if you can try that later.

**Comment by cpadillla1331** [comment] 2022-01-14 05:31
Sounds good - I'm using 0.1.4-r285

I installed with:

git clone https://github.com/haowenz/chromap.git
cd chromap && make


________________________________

**Comment by haowenz** [comment] 2022-01-14 06:23
Could you try the new branch trim-hic-sam (#57) and see if the issue is fixed? I tried on my Hi-C data and I could then run SAMtools to convert the SAM output by Chromap to BAM.

**Comment by haowenz** [comment] 2022-01-14 16:22
My test results on other benchmark data look fine. So I merged this into the master branch. You can now try master branch. I will tag a new release soon.

**Comment by baozg** [comment] 2022-01-17 11:19
Sorry, I have met a install issue with `make` on master branch, I can try it with the updated conda version.

**Comment by haowenz** [comment] 2022-01-17 20:14
> Sorry, I have met a install issue with `make` on master branch, I can try it with the updated conda version.

It is now updated on bioconda.

**Comment by cpadillla1331** [comment] 2022-01-26 21:28
Sorry for the delay in testing, but the this seems to have solved the issue, I can now convert SAM to BAM with samtools

Thank you!

**Comment by haowenz** [comment] 2022-01-26 23:14
> Sorry for the delay in testing, but the this seems to have solved the issue, I can now convert SAM to BAM with samtools
> 
> Thank you!

Good to know. Close this issue.

**Closed by haowenz** 2022-01-26 23:14 UTC
Labels: bug
